blank_issues_enabled: false
contact_links:
  - name: ii's Stupid Mods
    url: https://discord.gg/iidk
    about: If you're having issues with the menu or any mods, join the Discord server! Our kind support team are here to assist you with help whenever.
