blank_issues_enabled: false
contact_links:
  - name: ii's Stupid Mods
    url: https://discord.gg/iidk
    about: For better help and communication, join the Discord! We have channels for creating suggestions, reporting bugs, and requesting help with mods!
